apiVersion: v1
kind: Service
metadata:
  name: ingest-redis
  namespace: leo-telemetry
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  selector:
    app: ingest-redis
  ports:
    - port: 6379
      targetPort: 6379
