apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-redis
  namespace: leo-telemetry
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
    app: ingest-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ingest-redis
  template:
    metadata:
      labels:
        app: ingest-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          args: ["--appendonly", "yes"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ingest-redis
