apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-redis
  namespace: leo-telemetry
  labels:
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.redis.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}
