"""Shared constants for the decode pipeline."""

from __future__ import annotations

import string

# AX.25 / HDLC framing.
AX25_FLAG_BITS = "01111110"
AX25_ADDRESS_BYTES = 7
AX25_CALLSIGN_BYTES = 6
AX25_ADDRESS_BYTE_SHIFT = 1
AX25_ADDRESS_EXTENSION_BIT = 0x01
AX25_MIN_ADDRESS_FIELDS = 2
AX25_CONTROL_BYTES = 1
AX25_CONTROL_AND_PID_BYTES = 2
AX25_FCS_BYTES = 2
MIN_FRAME_BYTES = (
    AX25_ADDRESS_BYTES * AX25_MIN_ADDRESS_FIELDS + AX25_CONTROL_BYTES
)
MIN_FCS_FRAME_BYTES = 1 + AX25_FCS_BYTES

# CW beacon decoding.
CW_NORAD_IDS: tuple[int, ...] = (31130,)
CW_CALLSIGN = "K5USL"
CW_DEST_CALLSIGN = "CQ"
CW_PACKET_TYPES = frozenset("123")
CW_HEX_DIGITS = frozenset(string.hexdigits.upper())
CW_PACKET_TYPE_CHARS = 1
CW_MIN_HEX_CHARS = 2
CW_MIN_BEACON_CHARS = (
    len(CW_CALLSIGN) + CW_PACKET_TYPE_CHARS + CW_MIN_HEX_CHARS
)

# Redis queue configuration.
DECODED_QUEUE_KEY = "leo_telemetry:decode:queue"
DEFAULT_DECODED_QUEUE_SIZE = 5000

# Decode service configuration.
REDIS_URL_ENV = "REDIS_URL"
DEFAULT_REDIS_URL = "redis://localhost:6379/0"
DECODE_POLL_INTERVAL_ENV = "DECODE_POLL_INTERVAL_SECONDS"
DEFAULT_DECODE_POLL_INTERVAL_SECONDS = 2.0
LOG_LEVEL_ENV = "LOG_LEVEL"
DEFAULT_LOG_LEVEL = "INFO"
