apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: leo-telemetry
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
