image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: 16927c14ae6c9a450872f6bd9bbdcd78dc1f1db4
config:
  logLevel: "INFO"
  demuxPollIntervalSeconds: "2.0"
  demuxMaxQueueSize: "5000"
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
