image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: 787596ece7c382e19eb463c36b741d0c0786dda4
config:
  logLevel: "INFO"
  demuxPollIntervalSeconds: "2.0"
  demuxMaxQueueSize: "5000"
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
