image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: bd73a4f71acc1b4668f5311a2447dd557254e2d3
config:
  logLevel: "INFO"
  demuxPollIntervalSeconds: "2.0"
  demuxMaxQueueSize: "5000"
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
