apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>CS467 - LEO Satellite Data-Link & Telemetry Dashboard</title>
        <style>
          body, html { margin: 0; padding: 0; height: 100%; font-family: sans-serif; }
          header { padding: 1rem; background: #111; color: white; }
          iframe { width: 100%; height: calc(100vh - 60px); border: none; }
        </style>
      </head>
      <body>
        <header><h2>LEO Telemetry Dashboard</h2></header>
        <iframe src="{{ .Values.grafanaUrl }}"></iframe>
      </body>
    </html>
