image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: e76b9bfbf3689e409b3ab54a1fee1fb274dcf883
config:
  noradIds: "60525,68458,31130"
  pollIntervalSeconds: "300"
  minRequestIntervalSeconds: "5"
  logLevel: "INFO"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
redis:
  image: redis:7-alpine
  storageSize: 1Gi
  storageClassName: local-path
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 256Mi
postgres:
  image: postgres:16-alpine
  dbName: leo_telemetry
  appUser: ingest
  readonlyUser: decode_readonly
  storageSize: 2Gi
  storageClassName: local-path
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
