image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: a34402b4e45fce391b5f1ddea3f05262c26e9cee
config:
  logLevel: "INFO"
  decodePollIntervalSeconds: "2"
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
