image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: 59646a01403796aefdf7b1bb7496c27d0a21aafb
config:
  logLevel: "INFO"
  decodePollIntervalSeconds: "2"
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
