apiVersion: v1
kind: Service
metadata:
  name: observability-metrics
  namespace: leo-telemetry
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  selector:
    app: observability
  ports:
    - name: metrics
      port: {{ .Values.config.metricsPort }}
      targetPort: metrics
