image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: e954eb93db764cb3702158a15e2cb6a751009e3d
config:
  logLevel: "INFO"
  obsPollIntervalSeconds: "2.0"
  metricsPort: "8000"
  tleRefreshSeconds: "21600"
  positionUpdateSeconds: "15"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
