image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: a34402b4e45fce391b5f1ddea3f05262c26e9cee
config:
  logLevel: "INFO"
  obsPollIntervalSeconds: "2.0"
  metricsPort: "8000"
  tleRefreshSeconds: "21600"
  positionUpdateSeconds: "15"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
