image:
  repository: ghcr.io/danier54/leo-telemetry-ingest
  tag: 4e0e5fa0d862744d794d45bc17a3397d48b5328f
config:
  logLevel: "INFO"
  obsPollIntervalSeconds: "2.0"
  metricsPort: "8000"
  tleRefreshSeconds: "21600"
  positionUpdateSeconds: "15"
resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
